### ISSUE TITLE
TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by felipefmoreira** [netodeolino/TCC#1]
Olá, gostaria inicialmente de agradecer pela disponibilização do código. Estou utilizando seu código na minha pesquisa de mestrado sobre avaliação de imóveis.

Encontrei um erro ao executar o script `mainExtractMany.py`. Fiz todo o procedimento e formatei os arquivos de acordo como especificado pelo script porém ao executar ele dá o erro `TypeError: 'float' object is not iterable`.

Traceback:

```
Traceback (most recent call last):
  File "mainExtractMany.py", line 32, in <module>
    "tabula-29-jan-17", "tabula-30-jan-17", "tabula-31-jan-17"
  File "/Users/felipe/Documentos/Python/Crimes/Extrair Muitos Arquivos/extractMany.py", line 284, in main
    self.extractHistoricoDaOcorrencia(dataFrameInicial, dataFrameOriginal)
  File "/Users/felipe/Documentos/Python/Crimes/Extrair Muitos Arquivos/extractMany.py", line 172, in extractHistoricoDaOcorrencia
    self.insertDataFrameValues(self.entities[e], arrayRow, dataFrameOriginal)
  File "/Users/felipe/Documentos/Python/Crimes/Extrair Muitos Arquivos/extractMany.py", line 150, in insertDataFrameValues
    valor = self.extractOneEntityFromRow(arrayRow, entity, t)
  File "/Users/felipe/Documentos/Python/Crimes/Extrair Muitos Arquivos/extractMany.py", line 75, in extractOneEntityFromRow
    stringRow = self.arrayToString(arrayRow[position])
  File "/Users/felipe/Documentos/Python/Crimes/Extrair Muitos Arquivos/extractMany.py", line 21, in arrayToString
    for strIterator in strCell:
TypeError: 'float' object is not iterable
```

Consegue imaginar o que seria a causa do problema?

**Comment by netodeolino** [comment]
Está usando a versão 3.5 do python? Assim que eu tiver um tempo vou tentar executar novamente para ver se posso lhe ajudar melhor!

**Comment by felipefmoreira** [comment]
Oi, @netodeolino, eu uso Python 3.7. Acabei conseguindo contornar o problema adicionando `str()` no termo `strCell` em cada parte do loop.

Agradeço novamente pelo script que você disponibilizou.

**Comment by netodeolino** [comment]
Certo Felipe, qualquer coisa pode mandar email!
